// ---------------------------------------------------------------------------
// 🍃 JetLeaf Framework - https://jetleaf.hapnium.com
//
// Copyright © 2025 Hapnium & JetLeaf Contributors. All rights reserved.
//
// This source file is part of the JetLeaf Framework and is protected
// under copyright law. You may not copy, modify, or distribute this file
// except in compliance with the JetLeaf license.
//
// For licensing terms, see the LICENSE file in the root of this project.
// ---------------------------------------------------------------------------
// 
// 🔧 Powered by Hapnium — the Dart backend engine 🍃

import 'dart:math';
import 'dart:typed_data';

import '../exceptions.dart';

/// {@template uuid_range_builder}
/// Abstract base class for generating random numbers used in UUID creation.
///
/// Provides a standardized interface for random number generation while ensuring
/// the output meets UUID requirements (16-byte length). Implementations can
/// provide different random number generation strategies (e.g., math-based or
/// cryptographically secure).
///
/// {@template uuid_range_builder_usage}
/// ## Usage
/// 
/// 1. Create a concrete implementation by extending this class
/// 2. Implement the `_generate()` method to produce 16 random bytes
/// 3. Use the `generate()` method to get validated random bytes
///
/// ```dart
/// class CustomUuidRangeBuilder extends UuidRangeBuilder {
///   @override
///   Uint8List _generate() {
///     // Implementation that returns 16 random bytes
///   }
/// }
/// ```
/// {@endtemplate}
///
/// {@template uuid_range_builder_validation}
/// ## Validation
/// Automatically validates that generated bytes are exactly 16 bytes long.
/// Throws [InvalidFormatException] if validation fails.
/// {@endtemplate}
/// {@endtemplate}
abstract class UuidRangeBuilder {
  const UuidRangeBuilder();

  /// {@template uuid_range_builder_generate}
  /// Generates and validates a 16-byte random number for UUID generation.
  ///
  /// Calls the implementing class's `_generate()` method and verifies the
  /// output length meets UUID requirements.
  ///
  /// {@macro uuid_range_builder_validation}
  ///
  /// Returns:
  /// - Uint8List containing exactly 16 random bytes
  ///
  /// Throws:
  /// - [InvalidFormatException] if length is not 16 bytes
  ///
  /// Example:
  /// ```dart
  /// final builder = MathUuidRangeBuilder();
  /// final randomBytes = builder.generate(); // Always returns 16 bytes
  /// ```
  /// {@endtemplate}
  Uint8List generate() {
    final uint8list = _generate();
    if (uint8list.length != 16) {
      throw InvalidFormatException(
        'The length of the Uint8list returned by the custom UuidRangeBuilder must be 16.',
      );
    } else {
      return uint8list;
    }
  }

  /// {@template uuid_range_builder_internal_generate}
  /// Internal method to be implemented by subclasses for actual random number generation.
  ///
  /// Must return a Uint8List containing exactly 16 random bytes.
  ///
  /// Implementations should:
  /// - Focus purely on random number generation
  /// - Not worry about length validation (handled by `generate()`)
  /// - Be as efficient as possible
  ///
  /// Returns:
  /// - Uint8List with 16 random bytes
  /// {@endtemplate}
  Uint8List _generate();
}

/// {@template math_rng}
/// Fast, non-cryptographic random number generator using dart:math.Random.
///
/// Suitable for most use cases where cryptographic security isn't required.
/// Approximately 2-3x faster than CryptoUuidRangeBuilder but not suitable for security-sensitive
/// applications.
///
/// {@template math_rng_usage}
/// ## Usage
///
/// ```dart
/// // Basic usage
/// final rng = MathUuidRangeBuilder();
/// 
/// // With fixed seed for reproducible results
/// final seededRng = MathUuidRangeBuilder(seed: 42);
/// ```
/// {@endtemplate}
///
/// {@template math_rng_performance}
/// ## Performance
/// Generates random numbers by:
/// 1. Creating 4 random 32-bit integers
/// 2. Splitting each into 4 bytes
/// 3. Combining into 16-byte buffer
/// {@endtemplate}
/// {@endtemplate}
class MathUuidRangeBuilder extends UuidRangeBuilder {
  final Random _rnd;

  /// {@template math_rng_constructor}
  /// Creates a math-based random number generator.
  ///
  /// Parameters:
  /// - [seed]: Optional seed value for reproducible random sequences.
  ///           If null, uses system time for initialization.
  ///
  /// Example:
  /// ```dart
  /// // Unseeded (different results each run)
  /// final rng1 = MathUuidRangeBuilder();
  /// 
  /// // Seeded (reproducible results)
  /// final rng2 = MathUuidRangeBuilder(seed: 12345);
  /// ```
  /// {@endtemplate}
  MathUuidRangeBuilder({int? seed}) : _rnd = seed != null ? Random(seed) : Random();

  @override
  Uint8List _generate() {
    final b = Uint8List(16);

    for (var i = 0; i < 16; i += 4) {
      var k = _rnd.nextInt(pow(2, 32).toInt());
      b[i] = k;
      b[i + 1] = k >> 8;
      b[i + 2] = k >> 16;
      b[i + 3] = k >> 24;
    }

    return b;
  }
}

/// {@template crypto_rng}
/// Cryptographically secure random number generator using dart:math.Random.secure().
///
/// Suitable for security-sensitive applications but may be slower than MathUuidRangeBuilder.
/// Uses the platform's cryptographic random number generator where available.
///
/// {@template crypto_rng_usage}
/// ## Usage
///
/// ```dart
/// final secureRng = CryptoUuidRangeBuilder();
/// final secureBytes = secureRng.generate();
/// ```
/// {@endtemplate}
///
/// {@template crypto_rng_security}
/// ## Security Notes
/// - Uses the platform's cryptographic primitives
/// - Suitable for generating UUIDs that need unpredictability
/// - May be slower than MathUuidRangeBuilder
/// {@endtemplate}
/// {@endtemplate}
class CryptoUuidRangeBuilder extends UuidRangeBuilder {
  /// {@template crypto_rng_constructor}
  /// Creates a cryptographically secure random number generator.
  ///
  /// Note: No seed can be specified as cryptographic generators manage their own seeding.
  ///
  /// Example:
  /// ```dart
  /// final secureRng = CryptoUuidRangeBuilder();
  /// ```
  /// {@endtemplate}
  const CryptoUuidRangeBuilder();

  static final _secureRandom = Random.secure();

  @override
  Uint8List _generate() {
    final b = Uint8List(16);

    for (var i = 0; i < 16; i += 4) {
      var k = _secureRandom.nextInt(pow(2, 32).toInt());
      b[i] = k;
      b[i + 1] = k >> 8;
      b[i + 2] = k >> 16;
      b[i + 3] = k >> 24;
    }

    return b;
  }
}